apiVersion: v2
name: bewritten
description: A Helm chart for Mythos AI Story Architect
type: application
version: 0.1.8
appVersion: "0.1.8"
dependencies:
  - name: postgresql
    version: 16.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
