apiVersion: v2
name: bewritten
description: A Helm chart for Mythos AI Story Architect
type: application
version: 0.1.1
appVersion: "0.1.1"
dependencies:
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
