{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bewritten.fullname" . }}-app-secrets
  labels:
    {{- include "bewritten.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.adminEmail }}: {{ .Values.env.BEWRITTEN_ADMIN_EMAIL | quote }}
  {{ .Values.secrets.keys.adminPassword }}: {{ .Values.env.BEWRITTEN_ADMIN_PASSWORD | quote }}
  {{ .Values.secrets.keys.appSecretKey }}: {{ .Values.env.BEWRITTEN_SECRET_KEY | quote }}
  {{ .Values.secrets.keys.dbPassword }}: {{ .Values.postgres.auth.password | quote }}
  {{ .Values.secrets.keys.redisPassword }}: {{ .Values.redis.password | quote }}
{{- end -}}
