apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bewritten.fullname" . }}
  labels:
    {{- include "bewritten.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bewritten.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bewritten.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: BEWRITTEN_API_PORT
              value: "8080"
            - name: BEWRITTEN_ADMIN_EMAIL
              value: {{ .Values.env.BEWRITTEN_ADMIN_EMAIL | quote }}
            - name: BEWRITTEN_ADMIN_PASSWORD
              value: {{ .Values.env.BEWRITTEN_ADMIN_PASSWORD | quote }}
            - name: BEWRITTEN_SECRET_KEY
              value: {{ .Values.env.BEWRITTEN_SECRET_KEY | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
