{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bewritten.fullname" . }}
  labels:
    {{- include "bewritten.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "bewritten.selectorLabels" . | nindent 6 }}
{{- end }}
