{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bewritten.fullname" . }}-postgres
  labels:
    {{- include "bewritten.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "bewritten.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end -}}
